version: '2.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  #  cassandra:
  #    image: cassandra:latest
  #    ports:
  #      - 7000:7000
  #      - 7001:7001
  #      - 7199:7199
  #      - 9042:9042
  #      - 9160:9160
  #    environment:
  #      - CASSANDRA_CLUSTER_NAME='cassandra-cluster'
  #      #- CASSANDRA_NUM_TOKENS=256
  #      # - CASSANDRA_LISTEN_ADDRESS=0.0.0.0  # HOSTNAME OR IP OF MACHINE
  #      - CASSANDRA_RPC_ADDRESS=0.0.0.0

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"

#  api:
#    image: api:0.1
#    container_name: api
#    ports:
#      - 8085:8085
#    networks:
#      - test-network

networks:
  default:
    external:
      name: test-network